DEVELOPER_PATH=`xcode-select --print-path`
export DEVELOPER_PATH

DEVELOPER_DIR=$DEVELOPER_PATH
export DEVELOPER_DIR

IPHONEOS_DEVELOPER_PATH=$DEVELOPER_PATH/Platforms/iPhoneOS.platform/Developer
export IPHONEOS_DEVELOPER_PATH

PATH=$DEVELOPER_PATH/usr/bin:$IPHONEOS_DEVELOPER_PATH/usr/bin:$PATH
export PATH

