name: slack-pr-notify
on:
  pull_request:
    types: 
      - edited
jobs:
  slack:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: echo "${{ github.event.pull_request.user.email }}" 
      - run: bash ./.github/main.sh ${{ github.event.pull_request.title }}
      
#       - run: echo "${{ github.event.pull_request.title }}"
