on:
  pull_request:
    types: 
      - edited
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event.pull_request.title }} event."
