name: slack-pr-notify
on:
  pull_request:
    types: 
      - edited
jobs:
  slack:
      runs-on: ubuntu-latest
      steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Run Slack Script
      - run: ./.github/scripts/main.sh
        shell: bash
#       - run: echo "${{ github.event.pull_request.title }}"
