name: slack-pr-notify
on:
  pull_request:
    types: 
      - edited
jobs:
  slack:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Grab the PR author's email
        id: get_email
        run: |
          echo "pull_request_author_email=`git log origin/${{ github.base_ref }}..origin/${{ github.head_ref }} --pretty=format:%ae | head -1`" >> "$GITHUB_ENV"
      - name: Run slack bash script
      - run: bash ./.github/main.sh ${{ env.pull_request_author_email }} ${{ github.event.pull_request.title }}
      
    
